services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    image: dev-app
    container_name: vue-dev
    volumes:
      - ../..:/app
      - dev_modules:/app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  dev_modules:
    name: dev_modules