services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    image: prod-app
    container_name: vue-prod
    volumes:
      - prod_modules:/app/prod_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  prod_modules:
    name: prod_modules